import {
  ApplicationConfig,
  provideBrowserGlobalErrorListeners,
  provideZonelessChangeDetection,
  importProvidersFrom,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import {
  LucideAngularModule,
  Home,
  Briefcase,
  Dumbbell,
  FolderOpen,
  Star,
  CalendarDays,
  Search,
  Plus,
  User,
  Sun,
  Moon,
  Check,
  Trash2,
  Pencil,
  ChevronUp,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Circle,
  Flame,
  TrendingUp,
  ListTodo,
  LogOut,
  Heart,
  X,
  Flag,
  Bookmark,
  Tag,
  Clock,
  Calendar,
  AlertTriangle,
} from 'lucide-angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    // Zoneless change detection: removes Zone.js from the application entirely.
    // Angular relies exclusively on Signals and markForCheck() to schedule re-renders,
    // eliminating Zone.js's global async monkey-patching.
    // Benefits: smaller bundle, less per-event overhead, fully predictable reactivity.
    provideZonelessChangeDetection(),
    provideRouter(routes),
    provideAnimationsAsync(),
    importProvidersFrom(
      LucideAngularModule.pick({
        Home,
        Briefcase,
        Dumbbell,
        FolderOpen,
        Star,
        CalendarDays,
        Search,
        Plus,
        User,
        Sun,
        Moon,
        Check,
        Trash2,
        Pencil,
        ChevronUp,
        ChevronDown,
        ChevronRight,
        ChevronLeft,
        Circle,
        Flame,
        TrendingUp,
        ListTodo,
        LogOut,
        Heart,
        X,
        Flag,
        Bookmark,
        Tag,
        Clock,
        Calendar,
        AlertTriangle,
      }),
    ),
  ],
};
